config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :companies
  resources :owners

  resources :listings do
    resources :tasks
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#login'
  get 'logout' => 'sessions#logout'
  post 'logout' => 'sessions#logout'

  get 'password_reset' => 'authentication#change_password'
  put 'password_reset' => 'authentication#update_password'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, :uniqueness => true
  has_many :owners

end

app/models/listing.rb
class Listing < ActiveRecord::Base
    validates :address, :presence => true
    validates :owner_name, :presence => true
    validates :owner_email, :presence => true
    has_many :tasks

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates :password_digest, length: { minimum: 8 }

  belongs_to :company
  has_secure_password

end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, :uniqueness => true

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  belongs_to :listing



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    if logged_in?
      Company.find(session[:company_id])
    end

  end

  def logged_in?
    !!session[:company_id]
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def change_password
    token = params[:token]
    @owner = Owner.find_by_password_reset_token(token)
    if @owner.nil?
      flash[:error] = 'You have not requested a password reset.'
      redirect_to :root
    else
      render :change_password
    end
  end

  def update_password
    email = params[:owner][:email]
    new_password = params[:owner][:new_password]
    confirmation = params[:owner][:new_password_confirmation]
    @owner = Owner.find_by_email(email)

    if @owner.update_attributes(password: new_password.presence, password_confirmation: confirmation.presence)
      flash[:notice] = 'Your password has been reset. Please sign in with your new password.'
      redirect_to login_path
    else
      render :password_reset
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    email = params[:company][:email]
    password = params[:company][:password]
    password_confirmation = params[:company][:password_confirmation]

    @company = Company.create(:email => email, :password => password, :password_confirmation => password_confirmation)

    if @company.save
      Mailer.welcome_email(@company).deliver
      session[:company_id] = @company.id
      flash[:notice] = t('flash.company_creation.success')
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
    @listing = Listing.new
  end

  def index
    @listings = Listing.where(:seller_id => current_user)
  end


  def create
    address = params[:listing][:address]
    owner_name = params[:listing][:owner_name]
    owner_email = params[:listing][:owner_email]
    @listing = Listing.create(:address => address, :owner_name => owner_name, :seller_id => session[:company_id], :owner_email => owner_email)

    if @listing.save
      @company = current_user
      @owner = create_owner(owner_email, address, current_user)
      Mailer.invite_owner(@owner, @company).deliver
      flash[:notice] = t('flash.listing_creation.success')
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @owner = Owner.where(:company_id => params[:id])
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    address = params[:listing][:address]
    owner_name = params[:listing][:owner_name]
    @listing.update_attributes(:address => address, :owner_name => owner_name)
    if @listing.save
      flash[:notice] = t('flash.listing_creation.updated')
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:notice] = t('flash.listing_creation.deleted')
    redirect_to root_path
  end

  private

  def create_owner (email, address, current_user)
    email = email
    password_reset_token = SecureRandom.urlsafe_base64
    company_id = current_user
    password = generate_password
    Owner.create(:email => email, :password => password, :password_confirmation => password, :address => address, :company_id => company_id, :password_reset_token => password_reset_token)

  end

  def generate_password
    (0...50).map { ('a'..'z').to_a[rand(26)] }.join
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new

  end
  def create

  end

  def show
    @owner = Owner.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @company = Company.new
  end

  def login
    email = params[:company][:email]
    password = params[:company][:password]
    @company = Company.find_by_email(email)

    if @company && @company.authenticate(password)
      session[:company_id] = @company.id
      redirect_to root_path
    else
      flash[:notice] = "Email or Password Incorrect"
      render :new
    end
  end

  def logout
    session.clear
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
    name = params[:task][:name]
    description = params[:task][:description]
    seller = current_user
    finish_by = params[:task][:finish_by]
    Task.create(:name => name, :description => description, :seller_id => seller, :listing_id => params[:listing_id], :finish_by => finish_by)
    redirect_to listing_path(params[:listing_id])
  end

  def show
    @task = Task.find(params[:id])
    @listing = Listing.find(params[:listing_id])
  end

  def edit
    @task = Task.find(params[:id])
    @listing = Listing.find(params[:listing_id])
  end

  def update
    @task = Task.find(params[:id])
    @listing = Listing.find(params[:listing_id])
    name = params[:task][:name]
    description = params[:task][:description]
    finish_by = params[:task][:finish_by]
    completed = params[:task][:completed]

    @task.update(:name => name, :description => description, :listing_id => params[:listing_id], :finish_by => finish_by, :completed => completed)
    if @task.save
      flash[:notice] = "Task Updated"
      redirect_to listing_path(params[:listing_id])
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id]).delete
    redirect_to listing_path(params[:listing_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      @listings = Listing.where(:seller_id => session[:seller_id].to_s)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/change_password.html.erb
<p class="publication_title"><%= @owner.email %> Please set your password: </p>
<%= form_for @owner, :as => :owner, :url => password_reset_path, :method => :put do |f| %>
  <table class="form_styling">
    <tr>
      <td><%= f.label 'new password :' %></td>
      <td><%= f.password_field :new_password %></td>
    </tr>

    <tr>
      <%= f.hidden_field :email %>
      <td> <%= f.label 'password confirmation:' %></td>
      <td> <%= f.password_field :new_password_confirmation %></td>
    </tr>
    <tr>
      <td> <%= f.submit 'Update' %></td>
    </tr>
<% end %>
</table>

app/views/companies/new.html.erb
<% if @company.errors.present? %>
  <ul>
    <% @company.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>Create an Account</h2>

<%= form_for @company do |f| %>
  <div class="full_column">
    <fieldset>
      <p><%= f.label :email, 'Email', class: 'field_style' %>
        <%= f.text_field :email, class: 'text_box_style', autofocus: 'autofocus' %></p>

      <p><%= f.label :password, 'Password', class: 'field_style' %>
        <%= f.password_field :password, class: 'text_box_style' %></p>

      <p><%= f.label :password_confirmation, 'Password confirmation', class: 'field_style' %>
        <%= f.password_field :password_confirmation, class: 'text_box_style' %></p>

      <p> <%= f.submit 'Register', class: 'submit_button', style: 'font-size: 14px;' %></p>
    </fieldset>
  </div>
<% end %>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Real Estate APP</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed|Roboto|Roboto+Slab' rel='application' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<header>
  <% if current_user %>
    <div class="logout"> <%= link_to 'Logout', logout_path %></div>
    <div class="username"> <%= current_user.email %></div>
    <div id="header_container">
  <% end %>
  </div>
</header>
<% if flash.each do |name, msg| %>
  <div class="welcome_flash">
    <%= content_tag :div, msg, class: name %>
<% end %>
  </div>
<% end %>
<div id="content_container">
  <%= yield %>
</div>

<footer>
</footer>
</body>
</html>

app/views/listings/edit.html.erb
<% if @listing.errors.present? %>
  <ul>
    <% @listing.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @listing do |f| %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :owner_name %>
  <%= f.text_field :owner_name %>

  <%= f.submit :update %>

<% end %>

app/views/listings/index.html.erb
<table class="table table-striped">
  <th>Listing Address</th>
  <th>Listing Owner</th>
  <% @listings.each do |listing| %>
    <tr>
    <td><%= button_to listing.address, listing_path(listing), method: "get", class: "butn btn-primary" %> </td>
    <td><%= button_to listing.owner_name, owner_path(listing), method: "get", class: "butn btn-primary" %></td>

    </tr>
  <% end %>
</table>

<%= button_to "My Listings", listings_path, method: "get", class: "butn btn-primary" %>

app/views/listings/new.html.erb
<% if @listing.errors.present? %>
  <ul>
    <% @listing.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= notice %>


<div class="wrapper">
  <div class="row">
    <div class="content-main">

      <%= form_for @listing do |f| %>
        <div class="form-group">
          <%= f.label :address %>
          <div class="col-sm-12">
            <%= f.text_field :address %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :owner_name %>
          <div class="col-sm-12">
            <%= f.text_field :owner_name %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :owner_email %>
          <div class="col-sm-12">
            <%= f.text_field :owner_email %>
            <div class="form-group">
              <div class="col-sm-12">
                <br>
                <%= f.submit "Create Listing", class: "butn btn-success" %>
              </div>
      <% end %>
      </div>
</div>

app/views/listings/show.html.erb
<h1> <%= @listing.address %></h1>
<%= link_to "Edit Listing", edit_listing_path(@listing) %><br>
<%= link_to "Delete", listing_path, method: :delete, confirm: "Are you sure?" %><br>
<%= @listing.owner_name %>
<h2>Tasks:</h2>
<%= button_to "Create New Task", new_listing_task_path(@listing), method: "get" %>
<br>

<table class="table table-striped">
  <tr>
  <th>Task Title</th>
  <th>Completed</th>
  <th>Finish By</th>
  <th>Delete</th>
  </tr>
  <% @listing.tasks.each do |x| %>
    <tr>
      <td><%= button_to x.name, listing_task_path(:listing_id => @listing, :id => x), method: "get", class: "butn btn-primary" %></td>
      <% if x.completed? %>
      <td>Yes</td>
       <% else %>
      <td>No</td>
        <% end %>
      <td><%= x.finish_by%></td>
      <td><%= button_to "Delete", listing_task_path(:listing_id => @listing, :id => x), method: "delete", class: "butn btn-danger" %></td>
    </tr>
  <% end %>
</table>

app/views/owners/show.html.erb
<%= @owner.name %>
<%= @owner.email %>
<%= @owner.address %>

app/views/tasks/edit.html.erb
<% if @task.errors.present? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@listing, @task] do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description, style: "width: 300px; height: 150px;"%></td>
    </tr>
    <tr>
      <td><%= f.label :finish_by %></td>
      <td><%= f.text_field :finish_by, style: "width: 300px; height: 15px;"%></td>
    </tr>
    <tr>
      <td><%= f.label :completed %></td>
      <td><%= f.check_box :completed, style: "width: 300px; height: 15px;"%></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit :edit_task, :value => "Edit Task" %></td>
    </tr>
<% end %>
</table>

app/views/tasks/new.html.erb
<% if @task.errors.present? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="wrapper">
  <div class="content-main">
    <div class="row">
      <%= form_for [@listing, @task], html: {class: 'form-horizontal'} do |f| %>
        <div class="form-group">
          <%= f.label :task_name %>
          <div class="col-sm-12">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <div class="col-sm-12">
            <%= f.text_area :description, style: "width: 300px; height: 150px;" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :finish_by %>
          <div class="col-sm-12">
            <%= f.text_field :finish_by, style: "width: 300px; height: 30px;" %>

          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-10">

            <%= f.submit "Create Task", :value => "Create Task" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<h1><%= @listing.address %></h1>
<%= link_to "Edit", edit_listing_task_path(:listing_id => @task.listing_id, :id => @task.id)%>
<%= link_to "Delete", listing_task_path, method: :delete, confirm: "Are you sure?" %>


<h2>Name:</h2>
<%= @task.name %>
<br>
<h2>Description:</h2>
<%= @task.description %>
<br>
<h2>Finish by:</h2>
<%= @task.finish_by %>

<h2>Completed :</h2>
<% if @task.completed? %>
<%= "Yes" %>
<% else %>
<%= "No" %>
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<h1>Hello</h1>

<% if current_user %>
<%= button_to "My Listings", listings_path, method: "get", class: "butn btn-primary" %>
<br>
<%= button_to "Create Listing", new_listing_path, method: "get", class: "butn btn-primary" %>

  <% else %>

<%= button_to "Register", new_company_path, method: "get", class: "butn btn-primary" %>
  <br>
<%= button_to "Login", login_path, method: "get", class: "butn btn-primary" %>

  <% end %>



<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>